# Generated by Django 5.0.2 on 2024-02-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_alter_perfilusuario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecousuario',
            name='cep',
            field=models.PositiveIntegerField(max_length=8),
        ),
    ]
