# Generated by Django 5.0.2 on 2024-02-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_alter_enderecousuario_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecousuario',
            name='cep',
            field=models.CharField(max_length=8),
        ),
    ]
