# Generated by Django 5.0.2 on 2024-02-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_perfilusuario_bairro_perfilusuario_cep_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnderecoUsuario',
        ),
    ]
