# Generated by Django 5.0.2 on 2024-02-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_alter_perfilusuario_bairro_alter_perfilusuario_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='bairro',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='cep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='cidade',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='complemento',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='endereco',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='numero',
            field=models.CharField(max_length=5),
        ),
    ]
