# Generated by Django 5.0.2 on 2024-02-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
                ('descricao_curta', models.TextField(max_length=200)),
                ('descricao_longa', models.TextField(max_length=255)),
                ('imagem', models.ImageField(blank=True, upload_to='imagem_produto/%Y/%m/')),
                ('preço_marketing', models.FloatField(default=0)),
                ('preço_marketing_promocional', models.FloatField(default=0)),
                ('tipo', models.CharField(choices=[('V', 'Variação'), ('S', 'Simples')], default='V', max_length=1)),
            ],
        ),
    ]
