# Generated by Django 5.0.2 on 2024-02-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_variacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variacao',
            old_name='prduto',
            new_name='produto',
        ),
    ]
