# Generated by Django 5.0.2 on 2024-02-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_rename_prduto_variacao_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'variações'},
        ),
    ]
