# Generated by Django 5.0.2 on 2024-02-11 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_produto_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preço_marketing',
            new_name='preco_marketing',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preço_marketing_promocional',
            new_name='preco_marketing_promocional',
        ),
    ]
