# Generated by Django 5.0.2 on 2024-02-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_rename_preço_marketing_produto_preco_marketing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variacao',
            old_name='stoque',
            new_name='estoque',
        ),
    ]
